# 日常笔记

## java中try catch finally代码中的具体执行顺序

+ `finally`块总是被执行，只有`finally`执行完成后，才会回来执行`try`或者`catch`块中的`return`或者`throw`语句，如果`finally`块中使用了`return`或者`throw`等终止方法的语句，则不会跳回执行，直接停止。
+ `throws`和`throw`的区别，`throws`是方法上的声明，`throw`是具体抛出异常的语句。
+ 运行时异常是由`RuntimeException`类以及子类的异常，是非受检异常，如NullPointerException，IndexOutOfBoundsExcption等，由于这类异常要么是系统异常，无法处理，如网络问题：要么是程序逻辑错误，如空指针异常，`JVM`必须停止运行以改正这种错误，所以运行时异常可以不进行处理（捕获或向上抛出，当然也可以处理），而由`JVM`进行自行处理，`Java Runtime`会自动`catch`到程序`throw`的`RuntimeExcption`，然后停止线程，打印异常。五种常见的运行时异常：
`ClassCastException`,`IndexOutOfBoundsException`,`NullPointerException`,`ArrayStoreException`（数据存储异常，操作数组时类型不一致）,`BufferedOverflowException`（缓冲区上溢异常）。
+ 非运行时异常是指`RuntimeException`以外的异常，类型上都属于`Exception`类及其子类，是受检查的异常，非运行时异常必须进行处理，（捕获或者向上抛出），如果不做处理，程序将出现编译错误，一般情况下，API中写了`throws`的`Exception`都不是`RuntimeException`。

## java中的this所有用法
+ 引用成员变量
+ 在自身构造方法内部引用其他构造方法
+ 代表自身类的对象
+ 引用成员方法（均可省略）